language: python
dist: xenial
python:
  - "3.7"
  - "3.6"
  - "3.5"
cache:
  directories:
    - "$HOME/.cache/pip"
    - ".tox"

install:
  - pip install --upgrade pip wheel
  - pip install tox-travis
script: tox
after_success:
  - tox -e coverage,codecov
